# Generated by Django 5.2.7 on 2025-11-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_reference_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
